name: Master Branch

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test

  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-18.04
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/$REPO:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/$REPO:latest

  deploy:
    name: Deploy to K8s
    runs-on: ubuntu-18.04
    needs: [docker]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - name: Generate kube config file
        run: gcloud container clusters get-credentials  sample_cluster --zone=${{ secrets.CLUSTER_ZONE }}
      - name: Setup Helm3
        run: |-
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Deploy
        run: helm upgrade -i -f ./deployment/helm/values.yaml github-actions-test ./deployment/helm/


